"""added outreach table

Revision ID: 03eab9e8ebac
Revises: 0fabcf71b516
Create Date: 2026-05-26 17:10:00.791453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03eab9e8ebac'
down_revision: Union[str, Sequence[str], None] = '0fabcf71b516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reddit_post_id', sa.String(), nullable=True),
    sa.Column('subreddit_name', sa.String(), nullable=True),
    sa.Column('author_username', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('post_url', sa.Text(), nullable=True),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('ai_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sequence_step', sa.String(), nullable=True),
    sa.Column('outreach_method', sa.String(), nullable=True),
    sa.Column('outreach_content', sa.Text(), nullable=True),
    sa.Column('outreach_response', sa.Text(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('next_action_at', sa.DateTime(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_utc', sa.DateTime(), nullable=True),
    sa.Column('outreach_sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reddit_post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outreach')
    # ### end Alembic commands ###
